name: infokuy
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  barcode_scan: ^0.0.3
  device_info: ^0.2.1
  http: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 
  uses-material-design: true
  assets:
    - assets/domba.png
    - assets/nino.jpg
  fonts:
      - family: Productsans
        fonts:
          - asset: assets/product_sans.ttf
